### ISSUE TITLE
How to achive a Inhomogeneous plasma distribution？

### ISSUE THREAD

**Issue by xiaowang119** [VadimRomansky/PICpp#1]
Hi! I want to adopt your PIC code in a large-scale plasma simulation. But the parameter allowing user to define a uneven plasma distribution isn't discovered in offered example inputfile.

**Comment by VadimRomansky** [comment]
Hi! I have not used this code for two years, because it has a lot of
problems with stability. Now i use Smilei code, and
i recommend you to use it because it is more stable and user-friendly. The
only one advantage of PICpp is that it does not need hdf5 libraries and can
be easily run on PC with Windows

There is not such parameter in input file. All setups are hardcoded and you
chose what you need before compilation by commenting some lines in the
beginning of Simulation::simulatr(). If you want use PICpp for uneven
plasma distribution you should write your own method
Simulation::initializeMySetup() in file initialization.cpp in which you set
distribution that you need. And then call this method in the
Simulation::simulate() method

ср, 20 апр. 2022 г. в 09:32, xiaowang ***@***.***>:

**Comment by xiaowang119** [comment]
Thanks a lot! I had tried the Smilei before. But it holds a explicit algorithm, which is hard to finish a large-scale simulation.

**Comment by VadimRomansky** [comment]
I am not sure that implicit algorithm can do it, but you can try, good
luck.
In some cases (especially relativistic) implicit scheme becomes useless -
every time step is too long, it's better to use explicit scheme with 10
times more grid points

ср, 20 апр. 2022 г. в 17:25, xiaowang ***@***.***>:

**Comment by xiaowang119** [comment]
That's ok! Be graetful to your patient reply and useful suggestion.

Best Wishes!

**Comment by VadimRomansky** [comment]
Also you can try iPic3d, for which this scheme was developed by Lapenta and
others.

ср, 20 апр. 2022 г. в 17:42, xiaowang ***@***.***>:

**Comment by xiaowang119** [comment]
Yes, I have comunicated with him, the same problem about definition 
 of plasma density appears in his code.
